#!/bin/bash

CHECKSTATUS=0
QUIETEXIT=0
INSTALL_ATTEMPT=0

if ! which datab >/dev/null; then
   CHECKSTATUS=$(($CHECKSTATUS | 1))
fi
if ! [ -f /usr/include/libssh2.h ] && ! [ -f /usr/lib/libssh2.so ]; then
   CHECKSTATUS=$(($CHECKSTATUS | 2))
fi
if ! [ -f /usr/include/argon2.h ] && ! [ -f /usr/lib/libargon2.so ]; then
   CHECKSTATUS=$(($CHECKSTATUS | 4))
fi

usage()
{
   echo "usage: $0 [-h | -t | -s | -i=INSTALL_ATTEMPT | -q]"
   echo "   -h print this message"
   echo "   -t print necessary make targets"
   echo "   -s print dependency status"
   echo "   -i prints installation success/failure message"
   echo "      where INSTALL_ATTEMPT is an octal number"
   echo "   -q always exit with 0"
   echo ""
   echo "exit status is an octal status value"
}

print_status()
{
   if (($CHECKSTATUS & 1)); then
      echo -e "     datab   \e[31mMISSING\e[0m"
   else
      echo -e "     datab   \e[32mPRESENT\e[0m"
   fi
   if (($CHECKSTATUS & 2)); then
      echo -e "   libssh2   \e[31mMISSING\e[0m"
   else
      echo -e "   libssh2   \e[32mPRESENT\e[0m"
   fi
   if (($CHECKSTATUS & 4)); then
      echo -e "    argon2   \e[31mMISSING\e[0m"
   else
      echo -e "    argon2   \e[32mPRESENT\e[0m"
   fi
}

print_install_status()
{
   if ! (($INSTALL_ATTEMPT & $CHECKSTATUS)); then
      return;
   fi

   echo -e "\e[2;7;31mFAILED TO INSTALL THE FOLLOWING:\e[0m"

   if (($INSTALL_ATTEMPT & $CHECKSTATUS & 1)); then
      echo -e "   \e[31m- datab\e[0m"
   fi

   if (($INSTALL_ATTEMPT & $CHECKSTATUS & 2)); then
      echo -e "   \e[31m- libssh2\e[0m"
   fi

   if (($INSTALL_ATTEMPT & $CHECKSTATUS & 4)); then
      echo -e "   \e[31m- argon2\e[0m"
   fi
}

print_targets()
{
   if (($CHECKSTATUS & 2)); then
      echo -n "install-libssh2 "
   fi
   if (($CHECKSTATUS & 4)); then
      echo -n "install-argon2 "
   fi
   if [ "$CHECKSTATUS" -gt 0 ]; then
      echo -n "install-datab "
   fi
}

while getopts "htsi:q" flag; do
   case $flag in
      h)
         usage
         ;;
      t)
         print_targets
         ;;
      s)
         print_status
         ;;
      i)
         INSTALL_ATTEMPT=$OPTARG
         print_install_status
         ;;
      q)
         QUIETEXIT=1
         ;;
      \?)
         usage
         ;;
   esac
done

if  [ QUIETEXIT ]; then
   exit 0;
fi

exit $CHECKSTATUS
