#!/bin/bash

CHECKSTATUS=0
QUIETEXIT=0
INSTALL_ATTEMPT=0
UNINSTALL_ATTEMPT=0

if ! [ -f /usr/include/butil/butil.h ]; then
   CHECKSTATUS=$(($CHECKSTATUS | 1))
fi
if ! [ -f /usr/include/libssh2.h ] && ! [ -f /usr/lib/libssh2.so ]; then
   CHECKSTATUS=$(($CHECKSTATUS | 2))
fi
if ! [ -f /usr/include/argon2.h ] && ! [ -f /usr/lib/libargon2.so ]; then
   CHECKSTATUS=$(($CHECKSTATUS | 4))
fi
if ! [ -f /usr/include/aes.h ] && ! [ -f /usr/lib/libtinyaes.so ]; then
   CHECKSTATUS=$(($CHECKSTATUS | 8))
fi

usage()
{
   echo "usage: $0 [-h | -t | -s | -i=INSTALL_ATTEMPT | -q]"
   echo "   -h print this message"
   echo "   -t print necessary make targets"
   echo "   -s print dependency status"
   echo "   -i prints installation success/failure message"
   echo "      where INSTALL_ATTEMPT is an octal number"
   echo "   -u prints uninstall success/failure message"
   echo "      where UNINSTALL_ATTEMPT is an octal number"
   echo "   -q always exit with 0"
   echo ""
   echo "library octal values:"
   echo "   butil:    001"
   echo "   libssh2:  002"
   echo "   argon2:   004"
   echo "   tiny-aes: 010"
   echo ""
   echo "exit status is an octal status value"
}

print_status()
{
   if (($CHECKSTATUS & 1)); then
      echo -e "     butil   \e[31mMISSING\e[0m"
   else
      echo -e "     butil   \e[32mPRESENT\e[0m"
   fi
   if (($CHECKSTATUS & 2)); then
      echo -e "   libssh2   \e[31mMISSING\e[0m"
   else
      echo -e "   libssh2   \e[32mPRESENT\e[0m"
   fi
   if (($CHECKSTATUS & 4)); then
      echo -e "    argon2   \e[31mMISSING\e[0m"
   else
      echo -e "    argon2   \e[32mPRESENT\e[0m"
   fi
   if (($CHECKSTATUS & 8)); then
      echo -e "  tiny-aes   \e[31mMISSING\e[0m"
   else
      echo -e "  tiny-aes   \e[32mPRESENT\e[0m"
   fi
}

print_install_status()
{
   if ! (($INSTALL_ATTEMPT & $CHECKSTATUS)); then
      return;
   fi

   echo -e "\e[2;7;31mFAILED TO INSTALL THE FOLLOWING:\e[0m"

   if (($INSTALL_ATTEMPT & $CHECKSTATUS & 1)); then
      echo -e "   \e[31m- butil\e[0m"
   fi

   if (($INSTALL_ATTEMPT & $CHECKSTATUS & 2)); then
      echo -e "   \e[31m- libssh2\e[0m"
   fi

   if (($INSTALL_ATTEMPT & $CHECKSTATUS & 4)); then
      echo -e "   \e[31m- argon2\e[0m"
   fi

   if (($INSTALL_ATTEMPT & $CHECKSTATUS & 8)); then
      echo -e "   \e[31m- tiny-aes\e[0m"
   fi
}

print_uninstall_status()
{
   if ! (($UNINSTALL_ATTEMPT & ~$CHECKSTATUS)); then
      return;
   fi

   echo -e "\e[7;33mFAILED TO UNINSTALL THE FOLLOWING:\e[0m"

   if (($UNINSTALL_ATTEMPT & ~$CHECKSTATUS & 1)); then
      echo -e "   \e[33m- butil\e[0m"
   fi

   if (($UNINSTALL_ATTEMPT & ~$CHECKSTATUS & 2)); then
      echo -e "   \e[33m- libssh2\e[0m"
   fi

   if (($UNINSTALL_ATTEMPT & ~$CHECKSTATUS & 4)); then
      echo -e "   \e[33m- argon2\e[0m"
   fi

   if (($UNINSTALL_ATTEMPT & ~$CHECKSTATUS & 8)); then
      echo -e "   \e[33m- tiny-aes\e[0m"
   fi
}

print_targets()
{
   if (($CHECKSTATUS & 1)); then
      echo -n "install-butil "
   fi
   if (($CHECKSTATUS & 2)); then
      echo -n "install-libssh2 "
   fi
   if (($CHECKSTATUS & 4)); then
      echo -n "install-argon2 "
   fi
   if (($CHECKSTATUS & 8)); then
      echo -n "install-tiny-aes"
   fi
}

optarg_decimal()
{
   echo $(bc <<< "obase=10;ibase=8;$OPTARG")
}

while getopts "htsi:u:q" flag; do
   case $flag in
      h)
         usage
         ;;
      t)
         print_targets
         ;;
      s)
         print_status
         ;;
      i)
         INSTALL_ATTEMPT=$(optarg_decimal)
         print_install_status
         ;;
      u)
         UNINSTALL_ATTEMPT=$(optarg_decimal)
         print_uninstall_status
         ;;
      q)
         QUIETEXIT=1
         ;;
      \?)
         usage
         ;;
   esac
done

if  [ QUIETEXIT ]; then
   exit 0;
fi

exit $CHECKSTATUS
